// export const SET_NAME = 'SET_NAME'
// export const SET_LASTNAME = 'SET_LASTNAME'
export const SET_ID = 'SET_ID'
export const SET_ITEM = 'SET_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
// export const SET_CNT = 'SET_CNT'